services:
  - type: web
    name: cobraq
    dockerfilePath: ./Dockerfile
    region: singapore
    plan: free
    healthCheckPath: /health
    envVars:
      - key: APP_ENV
        value: production
      - key: DB_ENGINE
        value: sqlite
